<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVexSx7z\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVexSx7z/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerVexSx7z.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerVexSx7z\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerVexSx7z\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'VexSx7z',
    'container.build_id' => '31cd7d69',
    'container.build_time' => 1559468212,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVexSx7z');
