<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8hgA6s\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8hgA6s/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerY8hgA6s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerY8hgA6s\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerY8hgA6s\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'Y8hgA6s',
    'container.build_id' => '2b339d4e',
    'container.build_time' => 1558058003,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8hgA6s');
