<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmDGGKU\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmDGGKU/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWmDGGKU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWmDGGKU\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerWmDGGKU\srcApp_KernelProdContainer([
    'container.build_hash' => 'WmDGGKU',
    'container.build_id' => 'd2185dd6',
    'container.build_time' => 1552563216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmDGGKU');
