<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqD85os\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqD85os/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerZqD85os.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerZqD85os\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerZqD85os\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'ZqD85os',
    'container.build_id' => '233aed21',
    'container.build_time' => 1559870390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqD85os');
