<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.fa8f03f5.js',
                '/build/app.0211c23e.js',
            ],
            'css' => [
                '/build/app.957e1af3.css',
            ],
        ],
    ],
],

]];
