<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6R9gNN2' shared service.

return $this->privates['.service_locator.6R9gNN2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'question' => ['privates', '.errored..service_locator.6R9gNN2.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.6R9gNN2": it references class "App\\Entity\\Question" but no such service exists.'],
]);
