<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\QuestionController::delete' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController::edit' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController::index' => ['privates', '.service_locator.2nLzZDj', 'get_ServiceLocator_2nLzZDjService.php', true],
    'App\\Controller\\QuestionController::show' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController:delete' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController:edit' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController:index' => ['privates', '.service_locator.2nLzZDj', 'get_ServiceLocator_2nLzZDjService.php', true],
    'App\\Controller\\QuestionController:show' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
]));
