#index:
#    path: /
#    controller: App\Controller\DefaultController::index
question_index:
      path: /question
      controller: App\Controller\QuestionController::index
question_new:
      path: /question/new
      controller: App\Controller\QuestionController::new
question_show:
      path: /question/{id}
      controller: App\Controller\QuestionController::show
question_edit:
      path: /question/{id}/edit
      controller: App\Controller\QuestionController::edit
test_temp:
      path: /temp
      controller: App\Controller\MainController::temp