<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ParticipantAnswer extends \App\Entity\ParticipantAnswer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'answer', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'fk_question', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'fk_answeroption', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'participantAnswerAttributes', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'fk_testParticipation'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'answer', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'fk_question', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'fk_answeroption', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'participantAnswerAttributes', '' . "\0" . 'App\\Entity\\ParticipantAnswer' . "\0" . 'fk_testParticipation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ParticipantAnswer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer', []);

        return parent::getAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer(?string $answer): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer', [$answer]);

        return parent::setAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkQuestion(): ?\App\Entity\Question
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkQuestion', []);

        return parent::getFkQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkQuestion(?\App\Entity\Question $fk_question): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkQuestion', [$fk_question]);

        return parent::setFkQuestion($fk_question);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAnsweroption(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAnsweroption', []);

        return parent::getFkAnsweroption();
    }

    /**
     * {@inheritDoc}
     */
    public function addFkAnsweroption(\App\Entity\AnswerOption $fkAnsweroption): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFkAnsweroption', [$fkAnsweroption]);

        return parent::addFkAnsweroption($fkAnsweroption);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFkAnsweroption(\App\Entity\AnswerOption $fkAnsweroption): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFkAnsweroption', [$fkAnsweroption]);

        return parent::removeFkAnsweroption($fkAnsweroption);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipantAnswerAttributes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipantAnswerAttributes', []);

        return parent::getParticipantAnswerAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipantAnswerAttribute(\App\Entity\ParticipantAnswerAttribute $participantAnswerAttribute): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipantAnswerAttribute', [$participantAnswerAttribute]);

        return parent::addParticipantAnswerAttribute($participantAnswerAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipantAnswerAttribute(\App\Entity\ParticipantAnswerAttribute $participantAnswerAttribute): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipantAnswerAttribute', [$participantAnswerAttribute]);

        return parent::removeParticipantAnswerAttribute($participantAnswerAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkTestParticipation(): ?\App\Entity\TestParticipation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkTestParticipation', []);

        return parent::getFkTestParticipation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkTestParticipation(?\App\Entity\TestParticipation $fk_testParticipation): \App\Entity\ParticipantAnswer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkTestParticipation', [$fk_testParticipation]);

        return parent::setFkTestParticipation($fk_testParticipation);
    }

}
